export const PHONETIC_MNEMONICS = [
  { letter: 'A', codeWord: 'Alpha', mnemonic: 'Alpha males lead the pack' },
  { letter: 'B', codeWord: 'Bravo', mnemonic: 'Bravo! Well done performance' },
  { letter: 'C', codeWord: 'Charlie', mnemonic: 'Charlie Chaplin was famous' },
  { letter: 'D', codeWord: 'Delta', mnemonic: 'Delta airlines flies planes' },
  { letter: 'E', codeWord: 'Echo', mnemonic: 'Echo bounces off walls' },
  { letter: 'F', codeWord: 'Foxtrot', mnemonic: 'Foxtrot is a dance' },
  { letter: 'G', codeWord: 'Golf', mnemonic: 'Golf uses clubs and balls' },
  { letter: 'H', codeWord: 'Hotel', mnemonic: 'Hotels have many rooms' },
  { letter: 'I', codeWord: 'India', mnemonic: 'India has the Taj Mahal' },
  { letter: 'J', codeWord: 'Juliet', mnemonic: 'Juliet loved Romeo dearly' },
  { letter: 'K', codeWord: 'Kilo', mnemonic: 'Kilo means one thousand grams' },
  { letter: 'L', codeWord: 'Lima', mnemonic: 'Lima beans are green vegetables' },
  { letter: 'M', codeWord: 'Mike', mnemonic: 'Mike is short for microphone' },
  { letter: 'N', codeWord: 'November', mnemonic: 'November has Thanksgiving day' },
  { letter: 'O', codeWord: 'Oscar', mnemonic: 'Oscar awards honor movies' },
  { letter: 'P', codeWord: 'Papa', mnemonic: 'Papa means father everywhere' },
  { letter: 'Q', codeWord: 'Quebec', mnemonic: 'Quebec speaks French in Canada' },
  { letter: 'R', codeWord: 'Romeo', mnemonic: 'Romeo loved Juliet deeply' },
  { letter: 'S', codeWord: 'Sierra', mnemonic: 'Sierra mountains have snow' },
  { letter: 'T', codeWord: 'Tango', mnemonic: 'Tango takes two to dance' },
  { letter: 'U', codeWord: 'Uniform', mnemonic: 'Uniforms make everyone equal' },
  { letter: 'V', codeWord: 'Victor', mnemonic: 'Victor means winner always' },
  { letter: 'W', codeWord: 'Whiskey', mnemonic: 'Whiskey comes from Scotland' },
  { letter: 'X', codeWord: 'X-ray', mnemonic: 'X-rays see through bodies' },
  { letter: 'Y', codeWord: 'Yankee', mnemonic: 'Yankees play in New York' },
  { letter: 'Z', codeWord: 'Zulu', mnemonic: 'Zulu warriors were brave' },
];