import { Metadata } from 'next';
import { generateMetadata as baseGenerateMetadata } from '@/lib/seo/metadata';
import Link from 'next/link';

export const metadata: Metadata = baseGenerateMetadata(
  'Terms of Use',
  'Terms and conditions for using natophonetic.com: AI productivity tools and NATO comms training',
  '/terms'
);

const LAST_UPDATED = 'July 8, 2026';

export default function TermsPage() {
  return (
    <div className="container py-12 mb-24">
      <div className="max-w-3xl mx-auto prose prose-lg dark:prose-invert">
        <h1 className="text-5xl font-black tracking-headlines mb-8">Terms of Use</h1>

        <p className="text-xl text-secondary mb-8">Last updated: {LAST_UPDATED}</p>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Acceptance of Terms</h2>
          <p className="text-secondary">
            By accessing and using natophonetic.com, including the NATO comms training materials
            and the AI productivity tools, you agree to be bound by these Terms of Use. If you do
            not agree to these terms, please do not use the service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">The Service</h2>
          <p className="text-secondary">
            The platform provides two things: training resources for the NATO phonetic alphabet and
            radio-clear communication, and AI-powered productivity tools that draft, summarize,
            extract, and review text. Both are provided &quot;as is,&quot; free of charge, and
            without an account.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">AI Tools: Important Disclaimers</h2>
          <ul className="list-disc pl-6 space-y-2 text-secondary">
            <li>
              AI output is generated by third-party language models and can be incomplete,
              outdated, or wrong. It is a draft for you to verify, not professional, legal,
              medical, or operational advice.
            </li>
            <li>
              You are responsible for the text you submit. Do not submit information you lack
              permission to share, including confidential, classified, or regulated data. Inputs
              are processed by our AI providers as described in the{' '}
              <Link href="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              .
            </li>
            <li>
              You are responsible for reviewing AI output before using it in any real-world
              context, especially in safety-critical or mission-critical settings.
            </li>
            <li>
              Usage limits apply to keep the tools available to everyone; automated or bulk use is
              not permitted.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Acceptable Use</h2>
          <p className="text-secondary mb-4">You may:</p>
          <ul className="list-disc pl-6 space-y-2 text-secondary">
            <li>Use the platform for personal and professional work</li>
            <li>Use the training materials to learn and practice NATO comms</li>
            <li>Share links to the platform with others</li>
          </ul>
          <p className="text-secondary mt-4">You may not:</p>
          <ul className="list-disc pl-6 space-y-2 text-secondary">
            <li>Attempt to disrupt, overload, or interfere with the platform&apos;s operation</li>
            <li>Circumvent rate limits or access controls, or probe administrative areas</li>
            <li>Scrape or harvest data from the platform</li>
            <li>Use the AI tools to generate unlawful, harmful, or deceptive content</li>
            <li>Misrepresent the source or ownership of the content</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Reviews and Feedback</h2>
          <p className="text-secondary">
            By submitting a review or feedback you grant us permission to display it on the
            platform. Reviews are moderated before publication, and we may decline or remove any
            submission.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Disclaimer</h2>
          <p className="text-secondary">
            The materials and tools on this platform are provided on an &apos;as is&apos; basis. We
            make no warranties, expressed or implied, and hereby disclaim and negate all other
            warranties including, without limitation, implied warranties or conditions of
            merchantability, fitness for a particular purpose, or non-infringement of intellectual
            property.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Limitations</h2>
          <p className="text-secondary">
            In no event shall our platform or its suppliers be liable for any damages (including,
            without limitation, damages for loss of data or profit, or due to business
            interruption) arising out of the use or inability to use the materials or tools on our
            platform, including reliance on AI-generated output.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Accuracy of Materials</h2>
          <p className="text-secondary">
            While we strive to ensure accuracy, the materials appearing on our platform could
            include technical, typographical, or photographic errors. We do not warrant that any of
            the materials are accurate, complete, or current.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Links</h2>
          <p className="text-secondary">
            We have not reviewed all of the sites linked to our platform and are not responsible
            for the contents of any such linked site. The inclusion of any link does not imply
            endorsement. Use of any linked website is at the user&apos;s own risk.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Modifications</h2>
          <p className="text-secondary">
            We may revise these terms of use at any time without notice. By using this platform,
            you are agreeing to be bound by the then current version of these terms of use.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Contact Information</h2>
          <p className="text-secondary">
            If you have any questions about these Terms of Use, please visit our{' '}
            <Link href="/contact" className="text-primary hover:underline">
              contact page
            </Link>
            .
          </p>
        </section>

        <div className="mt-12 pt-8 border-t">
          <Link href="/" className="text-primary hover:underline">
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
